production_job:
  image: alpine:latest
  stage: deploy
  only: 
    - feat/set-up-ci-cd
  before_script:
    - apk add --update openssh-client bash
    - eval $(ssh-agent -s)
    - ping -c 3 18.191.78.155
    - bash -c 'ssh-add <(echo "$PROD_SSH_KEY")'
    - mkdir -p ~/.ssh
    - echo -e "$PROD_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f ./dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking=no\n\n" > ~/.ssh/config'
    # - ssh -o “StrictHostKeyChecking=no” -i ~/.ssh/id_rsa ubuntu@18.191.78.155 "echo 3232323232323232"
    - ssh-keyscan -H 'ec2-18-191-78-155.us-east-2.compute.amazonaws.com' >> ~/.ssh/known_hosts 
    - ssh-keyscan ec2-18-191-78-155.us-east-2.compute.amazonaws.com | sort -u - ~/.ssh/known_hosts -o ~/.ssh/known_hosts 
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

  script:
    - bash .gitlab-deploy-prod.sh