FROM node:12.19.0

RUN npm install -g nodemon
RUN npm install -g ts-node
RUN npm install -g typescript

WORKDIR /app

COPY package.json .

RUN yarn install

COPY . .

CMD ["yarn", "start:prod"]
# CMD ["sleep", "3000"]
